### ISSUE TITLE
Vereinheitlichung der Lizenz-URL in Liste der Lizenzen

### ISSUE THREAD

**Issue by kvlahrosch** [fraunhoferfokus/ogd-metadata#18]
In der Liste der Lizenzen zeigen die URL der einzelnen Lizenzen momentan manchmal auf die entsprechende Lizenzdefinition bei http://opendefinition.org, manchmal direkt auf die Website der Lizenz (zum Beispiel bei http://creativecommons.org).

Es wäre besser, wenn wir uns auf ein einheitliches Konzept für die Verlinkung einigen würde, also entweder alle Links auf http://opendefinition.org oder alle auf die jeweilige Lizenz-Website. Ich selbst bin für letztere Variante, da wir somit näher an der Quelle wären.

**Comment by akuckartz** [comment]
Eine Liste von Lizenzen / URLs zentral zur Auswahl anzubieten mag sinnvoll sein. Ich halte es aber für fragwürdig, eine solche Liste als abschliessend zu betrachten.

**Comment by benjamindittwald** [comment]
Die weitere Diskussion bitte hier führen: https://joinup.ec.europa.eu/asset/ogd2_0/issue/all
