### ISSUE TITLE
spatial-Format ist neu erfundenes Rad 

### ISSUE THREAD

**Issue by akuckartz** [fraunhoferfokus/ogd-metadata#20]
Das gegenwärtig für `spatial` vorgesehene Format ist vollkommen unüblich und auch unvollständig:
https://github.com/fraunhoferfokus/ogd-metadata/blob/master/OGPD_JSON_Schema.json

Nachdem wir uns im OParl-Projekt zunächst GeoJSON und dann GeoJSON-LD angesehen hatten, haben wir uns dort auf die Verwendung des etablierten Standards Well-Known Text WKT geeinigt. Siehe:
- http://en.wikipedia.org/wiki/Well-known_text
- https://github.com/OParl/specs/issues/103
- https://github.com/OParl/specs/issues/115
- https://github.com/OParl/specs/blob/master/dokument/master/chapter_8130.md
(Das ist "nur" ein Draft)

**Comment by akuckartz** [comment]
More than two years later the discussion is continued in https://joinup.ec.europa.eu/asset/ogd2_0/issue/geographic-extent

**Comment by benjamindittwald** [comment]
Damit kann diese Ticket geschlossen werden.
