### ISSUE TITLE
Categories as skos:Concept Linked Data objects

### ISSUE THREAD

**Issue by akuckartz** [fraunhoferfokus/ogd-metadata#21]
It would help if you would make the categories
https://github.com/fraunhoferfokus/ogd-metadata/blob/master/kategorien/iso.json
available as `skos:Concept` Linked Data objects. At least the formats JSON-LD and RDF Triple should be supported. And please interlink with EuroVoc and GEMET.

**Comment by akuckartz** [comment]
Auf govdata.de steht aktuell:

> Auf Grundlage von Interviews, Workshops mit Portalbetreibern aller Ebenen sowie weiteren Fachleuten, eigenen  Auswertungen sowie Abgleich mit vorhandenen Standards wird zur Zeit mit der Unterstützung der ]init[ AG ein neues Metadatenmodell entwickelt. 
https://www.govdata.de/standardisierung

3 von 6 der seit zwei Jahren offene Issues zu dem ersten Metadatenmodell sind von mir. "Interviews", Einladungen zu "Workshops" oder schlicht eine einfache Kontaktaufnahme mit mir gab es zu dem "neuen Metadatenmodell" meines Wissens nicht. Nach einem transparenten Verfahren sieht das für mich nicht aus. Das lässt bezüglich der für den 18.7.2016 angekündigten "Bewertung ... des Ergebnisses der öffentlichen Kommentierung" auch nur Pseudo-Offenheit erwarten.

**Comment by AntjeM** [comment]
Am kommenden Montag den 13.06. wird unter https://github.com/govdataofficial/ der aktuelle Arbeitsstand des neuen Metadatenmodells veröffentlicht. Bis zum 05.07.2016 sind dort dann alle eingeladen, diesen Stand zu kommentieren und Hinweise, Ergänzungen oder Kritik loszuwerden. Wir werden zu den Eingaben ebenfalls im GitHub Stellung nehmen, d.h. auch klären, welche Änderungen einfließen konnten und welche nicht.

**Comment by akuckartz** [comment]
Wie ich befürchtet hatte, wurde dieses Issue in den letzten zwei Jahren offenbar nicht berücksichtigt. Nun, immerhin wurde die bisher einzige vorgesehene öffentliche Review-Phase bereits zu Beginn auf etwas über einen Monat verlängert.

**Comment by k00ni** [comment]
@AntjeM: Leider kann ich unter deinem Link https://github.com/govdataofficial/ bisher keinen aktualisierten Arbeitsstand zum "neuen" Metadatenmodell (OGD 2.0?) finden. Wann wird dieser veröffentlicht? Ich nehme an im Repo `OGD-2.0` o.ä.?

**Comment by akuckartz** [comment]
@k00ni Der Entwurf wurde letztendlich nicht auf Github sondern auf Joinup veröffentlicht:
https://joinup.ec.europa.eu/asset/ogd2_0/home

**Comment by benjamindittwald** [comment]
Die weitere Diskussion bitte hier führen: https://joinup.ec.europa.eu/asset/ogd2_0/
